[package]
name = "embassy-ch58x"
version = "0.1.0-alpha.1"
edition = "2024"
rust-version = "1.87"
description = "Embassy async runtime support for WCH CH58x microcontrollers"
repository = "https://github.com/rusted-ch5/embassy-ch58x"
homepage = "https://github.com/rusted-ch5/embassy-ch58x"
license = "MIT OR Apache-2.0"
keywords = ["wch", "qingke", "embassy", "async", "no-std"]
categories = ["embedded", "no-std", "asynchronous", "hardware-support"]

[features]
default = ["ch582"]
ch582 = ["ch58x-hal/ch582", "qingke/v4", "qingke-rt/v4"]
ch585 = ["ch58x-hal/ch585", "qingke/v3", "qingke-rt/ch585-v3c"]
gpio = ["dep:embassy-sync", "dep:embedded-hal", "dep:embedded-hal-async"]
time-driver = ["dep:embassy-time-driver", "dep:embassy-time-queue-utils"]
uart = [
    "time-driver",
    "ch58x-hal/uart",
    "dep:embassy-sync",
    "dep:embassy-time",
    "dep:embedded-io",
    "dep:embedded-io-async",
]
usb = [
    "time-driver",
    "dep:embassy-sync",
    "dep:embassy-usb-driver",
    "dep:embassy-time",
]

[dependencies]
ch58x-hal = { git = "https://github.com/rusted-ch5/ch58x-hal.git", rev = "21400fecc7feb5cbd26b99a4367c10a91348712d", default-features = false }
critical-section = "1.2"
embassy-executor = { version = "0.9", features = ["executor-thread"] }
embassy-sync = { version = "0.8", optional = true }
embassy-time = { version = "0.5", features = ["tick-hz-1_000_000"], optional = true }
embassy-time-driver = { version = "0.2.2", features = ["tick-hz-1_000_000"], optional = true }
embassy-time-queue-utils = { version = "0.3.2", features = ["generic-queue-8"], optional = true }
embassy-usb-driver = { version = "0.2.2", optional = true }
embedded-hal = { version = "1.0", optional = true }
embedded-hal-async = { version = "1.0", optional = true }
embedded-io = { version = "0.6", optional = true }
embedded-io-async = { version = "0.6", optional = true }
portable-atomic = { version = "1.15", features = ["critical-section"] }
qingke = { version = "0.6.1", default-features = false }
qingke-rt = { git = "https://github.com/rusted-ch5/qingke-rs.git", rev = "b107f8b4cce3495ff807738cdbb34f25819ca680", default-features = false, features = ["highcode"] }

[workspace]
