name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.87"
          targets: riscv32imc-unknown-none-elf
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Check CH582
        run: cargo check --target riscv32imc-unknown-none-elf --no-default-features --features ch582,gpio,time-driver
      - name: Check CH585
        run: cargo check --target riscv32imc-unknown-none-elf --no-default-features --features ch585,gpio,time-driver
